<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H5KK288" failures="1" tests="3" name="FunctionalFlowTests" time="63.191" errors="0" timestamp="18 Mar 2020 15:18:19 GMT">
  <testcase classname="com.ecommerce.tests.FunctionalFlowTests" name="loginTest" time="2.162"/>
  <testcase classname="com.ecommerce.tests.FunctionalFlowTests" name="addDeleteProductsCheckout" time="42.131"/>
  <testcase classname="com.ecommerce.tests.FunctionalFlowTests" name="filterProductTest" time="1.934">
    <failure type="java.lang.AssertionError" message="expected [3] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [7]
	at com.ecommerce.tests.FunctionalFlowTests.filterProductTest(FunctionalFlowTests.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- filterProductTest -->
</testsuite> <!-- FunctionalFlowTests -->
